### ISSUE TITLE
dat. data file loading path problem

### ISSUE THREAD

**Issue by imu2326** [athulpg007/AMAT#1]
1.Example - 03 - Venus Aerocapture: Part 1
line 9:`planet.loadAtmosphereModel('.../atmdata/Venus/venus-gram-avg.dat', 0 , 1 ,2, 3)`
   I think there is a problem with this line of file index ,because you used /a in the path ,\a is escaped character sequence for control character BEL (a for alert). The character's ASCII code is also happened to be 7, which matches the octal value in the escape sequence \7 .
   For example, if I modify it to (`planet.loadAtmosphereModel('D:\mat/neptune-gram-avg.dat', 0, 1 ,2, 3)`), the problem is solved .

2.Example-12-neptune-aerocapture-part-2b
line 48:vehicle.runMonteCarlo(100, '../data/girijaSaikia2020b/MCB1') 
   Bug: FileExistsError: [WinError 183] When the file already exists, the file cannot be created. :'../data/girijaSaikia2020b/MCB1'
   I have not been able to solve this problem, but I think it is a path problem.

Thank u

**Comment by athulpg007** [comment]
1. If you are running these scripts from AMAT/examples/ directory, the atmdata directory is one level up, so it is loaded as
`planet.loadAtmosphereModel('../atmdata/Venus/venus-gram-avg.dat', 0 , 1 , 2, 3)`. I had no problems with this on Linux and Mac machines. I had done some testing on Windows machines as well (all 64-bit) and did not encounter the problem you mention. Maybe it is an issue with 32-bit Windows? You can modify the path to something else, if that can solve your problem.

2. You get the `FileExistsError` because `../data/girijaSaikia2020b/MCB1` already exists. You can either delete the MCB1 folder, or use a different folder name such as MCB2 instead.

**Comment by imu2326** [comment]
The problem has been solved, thank you for your help
